name: dsp-vehicle-segmentation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - matplotlib
      - pillow
      - torch>=2.1,<3
      - torchvision>=0.16,<1
      - opencv-python
      - ultralytics>=8.0,<9
      - segment-anything
      - streamlit
      - pyyaml